### ISSUE TITLE
nospell toggle?

### ISSUE THREAD

**Issue by jm3** [fkfk/vim-modeline#6]
Would you be willing to add support for `nospell` in modelines if the [spell-check](https://github.com/atom/spell-check) plugin is installed?

**Comment by fkfk** [comment]
Added `spell` and `nospell` support in the v0.5.2.
Please update vim-modeline.

**Comment by jm3** [comment]
Awesome! Thanks for the quick release! But.

Now if I Toggle the Spell-Check feature on, after opening a file with a nospell modeline, this error is thrown:

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package, v0.68.5

### Stack Trace

Uncaught TypeError: Cannot read property 'active' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/spell-check/lib/main.js:174

TypeError: Cannot read property 'active' of undefined
    at Object.toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/spell-check/lib/main.js:174:36)
    at atom-workspace.commandSubscription.atom.commands.add.spell-check:toggle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/spell-check/lib/main.js:64:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:00.0 spell-check:toggle (input.hidden-input)
```

(toggling Spell Check in a normal text file without a modeline still works fine)
